language: C++
os: linux
dist: focal

before_install:
- sudo apt-get install qt5-default qttools5-dev-tools
- sudo apt-get build-dep qt5-default
- sudo apt-get install libxcb-xinerama0-dev 
 

script:
 - qmake -project QT+= widgets
 - qmake
 - make
