language: C++
os: linux
dist: focal

before_install:
 - sudo apt-get install build-essentials
 - sudo apt-get build-dep
 - sudo apt-get install libxcb-xinerama0-dev
 - sudo apt-get install libx11-xcb-dev libglu1-mesa-dev
 - sudo apt-get install qt5-default
 

script:
 - qmake -project QT+= widgets
 - qmake
 - make
