#############################################################################
# Makefile for building: progetto_P2
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  progetto_P2.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile progetto_P2.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = progetto_P21.0.0
DISTDIR = /home/diego/Desktop/progetto_P2/.tmp/progetto_P21.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gioco/gioco.cpp \
		pedina/id.cpp \
		posizione.cpp \
		gioco/scacchi.cpp \
		gioco/scacchiera.cpp \
		main.cpp \
		view/chessbutton.cpp \
		view/mainwindow.cpp \
		pedina/pedina.cpp \
		pedina/scacchi/alfiere.cpp \
		pedina/scacchi/cavallo.cpp \
		pedina/scacchi/pedinascacchi.cpp \
		pedina/scacchi/pedone.cpp \
		pedina/scacchi/re.cpp \
		pedina/scacchi/regina.cpp \
		pedina/scacchi/torre.cpp \
		pedina/scacchi/movimentoCroce.cpp \
		pedina/scacchi/movimentoDiagonale.cpp \
		view/selettore_gioco.cpp \
		controller.cpp \
		tipogioco.cpp \
		view/selettore_promozione_scacchi.cpp qrc_resources.cpp \
		moc_chessbutton.cpp \
		moc_mainwindow.cpp \
		moc_selettore_gioco.cpp \
		moc_controller.cpp \
		moc_selettore_promozione_scacchi.cpp
OBJECTS       = gioco.o \
		id.o \
		posizione.o \
		scacchi.o \
		scacchiera.o \
		main.o \
		chessbutton.o \
		mainwindow.o \
		pedina.o \
		alfiere.o \
		cavallo.o \
		pedinascacchi.o \
		pedone.o \
		re.o \
		regina.o \
		torre.o \
		movimentoCroce.o \
		movimentoDiagonale.o \
		selettore_gioco.o \
		controller.o \
		tipogioco.o \
		selettore_promozione_scacchi.o \
		qrc_resources.o \
		moc_chessbutton.o \
		moc_mainwindow.o \
		moc_selettore_gioco.o \
		moc_controller.o \
		moc_selettore_promozione_scacchi.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		progetto_P2.pro colore.h \
		gioco/gioco.h \
		pedina/id.h \
		posizione.h \
		gioco/scacchi.h \
		gioco/scacchiera.h \
		view/chessbutton.h \
		view/mainwindow.h \
		pedina/pedina.h \
		pedina/scacchi/alfiere.h \
		pedina/scacchi/cavallo.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/scacchi/pedone.h \
		pedina/scacchi/re.h \
		pedina/scacchi/regina.h \
		pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/movimentoDiagonale.h \
		view/selettore_gioco.h \
		controller.h \
		tipogioco.h \
		view/selettore_promozione_scacchi.h gioco/gioco.cpp \
		pedina/id.cpp \
		posizione.cpp \
		gioco/scacchi.cpp \
		gioco/scacchiera.cpp \
		main.cpp \
		view/chessbutton.cpp \
		view/mainwindow.cpp \
		pedina/pedina.cpp \
		pedina/scacchi/alfiere.cpp \
		pedina/scacchi/cavallo.cpp \
		pedina/scacchi/pedinascacchi.cpp \
		pedina/scacchi/pedone.cpp \
		pedina/scacchi/re.cpp \
		pedina/scacchi/regina.cpp \
		pedina/scacchi/torre.cpp \
		pedina/scacchi/movimentoCroce.cpp \
		pedina/scacchi/movimentoDiagonale.cpp \
		view/selettore_gioco.cpp \
		controller.cpp \
		tipogioco.cpp \
		view/selettore_promozione_scacchi.cpp
QMAKE_TARGET  = progetto_P2
DESTDIR       = 
TARGET        = progetto_P2


first: all
####### Build rules

progetto_P2:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: progetto_P2.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		progetto_P2.pro \
		resources.qrc
	$(QMAKE) -o Makefile progetto_P2.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
progetto_P2.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile progetto_P2.pro

qmake_all: FORCE


all: Makefile progetto_P2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents colore.h gioco/gioco.h pedina/id.h posizione.h gioco/scacchi.h gioco/scacchiera.h view/chessbutton.h view/mainwindow.h pedina/pedina.h pedina/scacchi/alfiere.h pedina/scacchi/cavallo.h pedina/scacchi/pedinascacchi.h pedina/scacchi/pedone.h pedina/scacchi/re.h pedina/scacchi/regina.h pedina/scacchi/torre.h pedina/scacchi/movimentoCroce.h pedina/scacchi/movimentoDiagonale.h view/selettore_gioco.h controller.h tipogioco.h view/selettore_promozione_scacchi.h $(DISTDIR)/
	$(COPY_FILE) --parents gioco/gioco.cpp pedina/id.cpp posizione.cpp gioco/scacchi.cpp gioco/scacchiera.cpp main.cpp view/chessbutton.cpp view/mainwindow.cpp pedina/pedina.cpp pedina/scacchi/alfiere.cpp pedina/scacchi/cavallo.cpp pedina/scacchi/pedinascacchi.cpp pedina/scacchi/pedone.cpp pedina/scacchi/re.cpp pedina/scacchi/regina.cpp pedina/scacchi/torre.cpp pedina/scacchi/movimentoCroce.cpp pedina/scacchi/movimentoDiagonale.cpp view/selettore_gioco.cpp controller.cpp tipogioco.cpp view/selettore_promozione_scacchi.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/chess/style.css \
		resources/chess/icons/pawn_black.png \
		resources/chess/icons/rook_white.png \
		resources/chess/icons/rook_black.png \
		resources/chess/icons/king_white.png \
		resources/chess/icons/king_black.png \
		resources/chess/icons/queen_white.png \
		resources/chess/icons/knight_white.png \
		resources/chess/icons/knight_black.png \
		resources/chess/icons/queen_black.png \
		resources/chess/icons/bishop_white.png \
		resources/chess/icons/bishop_black.png \
		resources/chess/icons/pawn_white.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_chessbutton.cpp moc_mainwindow.cpp moc_selettore_gioco.cpp moc_controller.cpp moc_selettore_promozione_scacchi.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chessbutton.cpp moc_mainwindow.cpp moc_selettore_gioco.cpp moc_controller.cpp moc_selettore_promozione_scacchi.cpp
moc_chessbutton.cpp: view/chessbutton.h \
		posizione.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/diego/Desktop/progetto_P2/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/diego/Desktop/progetto_P2 -I/home/diego/Desktop/progetto_P2 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/chessbutton.h -o moc_chessbutton.cpp

moc_mainwindow.cpp: view/mainwindow.h \
		view/selettore_gioco.h \
		view/selettore_promozione_scacchi.h \
		view/chessbutton.h \
		posizione.h \
		pedina/id.h \
		colore.h \
		tipogioco.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/diego/Desktop/progetto_P2/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/diego/Desktop/progetto_P2 -I/home/diego/Desktop/progetto_P2 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/mainwindow.h -o moc_mainwindow.cpp

moc_selettore_gioco.cpp: view/selettore_gioco.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/diego/Desktop/progetto_P2/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/diego/Desktop/progetto_P2 -I/home/diego/Desktop/progetto_P2 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/selettore_gioco.h -o moc_selettore_gioco.cpp

moc_controller.cpp: controller.h \
		view/mainwindow.h \
		view/selettore_gioco.h \
		view/selettore_promozione_scacchi.h \
		view/chessbutton.h \
		posizione.h \
		pedina/id.h \
		colore.h \
		tipogioco.h \
		gioco/gioco.h \
		gioco/scacchiera.h \
		pedina/pedina.h \
		gioco/scacchi.h \
		pedina/scacchi/pedone.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/alfiere.h \
		pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/cavallo.h \
		pedina/scacchi/regina.h \
		pedina/scacchi/re.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/diego/Desktop/progetto_P2/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/diego/Desktop/progetto_P2 -I/home/diego/Desktop/progetto_P2 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controller.h -o moc_controller.cpp

moc_selettore_promozione_scacchi.cpp: view/selettore_promozione_scacchi.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/diego/Desktop/progetto_P2/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/diego/Desktop/progetto_P2 -I/home/diego/Desktop/progetto_P2 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/selettore_promozione_scacchi.h -o moc_selettore_promozione_scacchi.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

gioco.o: gioco/gioco.cpp gioco/gioco.h \
		gioco/scacchiera.h \
		posizione.h \
		pedina/pedina.h \
		colore.h \
		pedina/id.h \
		tipogioco.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gioco.o gioco/gioco.cpp

id.o: pedina/id.cpp pedina/id.h \
		colore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o id.o pedina/id.cpp

posizione.o: posizione.cpp posizione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posizione.o posizione.cpp

scacchi.o: gioco/scacchi.cpp gioco/scacchi.h \
		gioco/gioco.h \
		gioco/scacchiera.h \
		posizione.h \
		pedina/pedina.h \
		colore.h \
		pedina/id.h \
		tipogioco.h \
		pedina/scacchi/pedone.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/alfiere.h \
		pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/cavallo.h \
		pedina/scacchi/regina.h \
		pedina/scacchi/re.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scacchi.o gioco/scacchi.cpp

scacchiera.o: gioco/scacchiera.cpp gioco/scacchiera.h \
		posizione.h \
		pedina/pedina.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scacchiera.o gioco/scacchiera.cpp

main.o: main.cpp controller.h \
		view/mainwindow.h \
		view/selettore_gioco.h \
		view/selettore_promozione_scacchi.h \
		view/chessbutton.h \
		posizione.h \
		pedina/id.h \
		colore.h \
		tipogioco.h \
		gioco/gioco.h \
		gioco/scacchiera.h \
		pedina/pedina.h \
		gioco/scacchi.h \
		pedina/scacchi/pedone.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/alfiere.h \
		pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/cavallo.h \
		pedina/scacchi/regina.h \
		pedina/scacchi/re.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

chessbutton.o: view/chessbutton.cpp view/chessbutton.h \
		posizione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chessbutton.o view/chessbutton.cpp

mainwindow.o: view/mainwindow.cpp view/mainwindow.h \
		view/selettore_gioco.h \
		view/selettore_promozione_scacchi.h \
		view/chessbutton.h \
		posizione.h \
		pedina/id.h \
		colore.h \
		tipogioco.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o view/mainwindow.cpp

pedina.o: pedina/pedina.cpp pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pedina.o pedina/pedina.cpp

alfiere.o: pedina/scacchi/alfiere.cpp pedina/scacchi/alfiere.h \
		pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alfiere.o pedina/scacchi/alfiere.cpp

cavallo.o: pedina/scacchi/cavallo.cpp pedina/scacchi/cavallo.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cavallo.o pedina/scacchi/cavallo.cpp

pedinascacchi.o: pedina/scacchi/pedinascacchi.cpp pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pedinascacchi.o pedina/scacchi/pedinascacchi.cpp

pedone.o: pedina/scacchi/pedone.cpp pedina/scacchi/pedone.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pedone.o pedina/scacchi/pedone.cpp

re.o: pedina/scacchi/re.cpp pedina/scacchi/re.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o re.o pedina/scacchi/re.cpp

regina.o: pedina/scacchi/regina.cpp pedina/scacchi/regina.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h \
		pedina/scacchi/movimentoDiagonale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regina.o pedina/scacchi/regina.cpp

torre.o: pedina/scacchi/torre.cpp pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o torre.o pedina/scacchi/torre.cpp

movimentoCroce.o: pedina/scacchi/movimentoCroce.cpp pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movimentoCroce.o pedina/scacchi/movimentoCroce.cpp

movimentoDiagonale.o: pedina/scacchi/movimentoDiagonale.cpp pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/pedina.h \
		posizione.h \
		colore.h \
		pedina/id.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movimentoDiagonale.o pedina/scacchi/movimentoDiagonale.cpp

selettore_gioco.o: view/selettore_gioco.cpp view/selettore_gioco.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selettore_gioco.o view/selettore_gioco.cpp

controller.o: controller.cpp controller.h \
		view/mainwindow.h \
		view/selettore_gioco.h \
		view/selettore_promozione_scacchi.h \
		view/chessbutton.h \
		posizione.h \
		pedina/id.h \
		colore.h \
		tipogioco.h \
		gioco/gioco.h \
		gioco/scacchiera.h \
		pedina/pedina.h \
		gioco/scacchi.h \
		pedina/scacchi/pedone.h \
		pedina/scacchi/pedinascacchi.h \
		pedina/scacchi/torre.h \
		pedina/scacchi/movimentoCroce.h \
		pedina/scacchi/alfiere.h \
		pedina/scacchi/movimentoDiagonale.h \
		pedina/scacchi/cavallo.h \
		pedina/scacchi/regina.h \
		pedina/scacchi/re.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

tipogioco.o: tipogioco.cpp tipogioco.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tipogioco.o tipogioco.cpp

selettore_promozione_scacchi.o: view/selettore_promozione_scacchi.cpp view/selettore_promozione_scacchi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selettore_promozione_scacchi.o view/selettore_promozione_scacchi.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_chessbutton.o: moc_chessbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chessbutton.o moc_chessbutton.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_selettore_gioco.o: moc_selettore_gioco.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selettore_gioco.o moc_selettore_gioco.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_selettore_promozione_scacchi.o: moc_selettore_promozione_scacchi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selettore_promozione_scacchi.o moc_selettore_promozione_scacchi.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

